### ISSUE TITLE
GeoPoint property validation throw AssertionError

### ISSUE THREAD

**Issue by labkode** [strongloop/loopback-datasource-juggler#103]
When we have a schema like this

<pre>
{
    "location": {
        type:"GeoPoint",
        required: true
    }
}
</pre>

and we post a value for location which is not a GeoPoint representation of lat and lgn, like this

<pre>
{
    "age": "this is not a lat and lng"
}
</pre>

Instead of returning a "user friendly" like other validations, something  like this

<pre>
{
  "error": {
    "name": "ValidationError",
    "status": 422,
    "message": "The Model instance is not valid. See `details` property of the error object for more info.",
    "statusCode": 422,
    "details": {
      "context": "cancha",
      "codes": {
        "age": [
          "presence"
        ]
      },
      "messages": {
        "age": [
          "can't be blank"
        ]
      }
    },
    "stack": "ValidationError: The Model instance is not valid... "
  }
}
</pre>

Instead it throws an AssertionError killing the Node.js process 

<pre>
AssertionError: lat must be a number when creating a GeoPoint
    at new GeoPoint (/home/foo/bar/changa/node_modules/loopback-datasource-juggler/lib/geo.js:134:3)
</pre>

This force us to do the validation manually, thing  I don't know how to do. I tried with this without success

<pre>
try{
    Cancha.create({
        "location": "wrong geopoint"
    }, function(err, cancha){
        if(err)
            return console.log(err);
        return console.log(cancha.isValid());
    })
}catch(ev){
    console.log(ev);
}
</pre>

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by loay** [comment]
Closing due to inactivity. If you are still running into problems, feel free to leave a comment and I will reopen the issue.
Also, it looks like few solutions have been posted. 
Thanks.

**Comment by daamsie** [comment]
Yeah, this still needs a solution. I just ran into it with a latitude being entered that was over 90. Actually, just someone accidentally putting lat/lng the wrong way around. This should really be handled as a validation error inside the model type. 

The above are not solutions - they are workarounds, mostly avoiding GeoPoint altogether. It seems a shame to have a built in type like this that can't handle validation errors cleanly.

**Comment by peek4y** [comment]
@daamsie Exactly!

**Comment by loay** [comment]
re-opening issue

**Comment by ron137** [comment]
It is happen to me too, when I'm trying to enter wrong GeoPoint.
For example: { "lng": 180, "lat": 34}

**Comment by 0candy** [comment]
Hi All, I would like to clarify this issue. Is everyone saying that the app is crashing or that its not giving a user friendly error message?
I am unable to reproduce this error. My app does not crash and I get a user error message.
```
{
  "error": {
    "name": "AssertionError",
    "status": 500,
    "message": "lng must be <= 180",
    "actual": false,
    "expected": true,
    "operator": "==",
    "generatedMessage": false,
    "stack": "AssertionError: lng must be <= 180\n    at new GeoPoint (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/geo.js:166:3)\n    at GeoPoint (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/geo.js:131:12)\n    at ModelConstructor.set [as location] (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/model-builder.js:474:81)\n    at ModelConstructor.ModelBaseClass._initProperties (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/model.js:188:17)\n    at ModelConstructor.ModelBaseClass (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/model.js:55:8)\n    at ModelConstructor (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/model-builder.js:184:22)\n    at ModelConstructor (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/model-builder.js:184:22)\n    at new ModelConstructor (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/model-builder.js:184:22)\n    at Function.DataAccessObject.create (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/dao.js:286:11)\n    at Function.DataAccessObject.updateOrCreate.DataAccessObject.patchOrCreate.DataAccessObject.upsert (/Users/candy/loopback/triage/postgres/node_modules/loopback-datasource-juggler/lib/dao.js:480:17)\n    at SharedMethod.invoke (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:263:25)\n    at HttpContext.invoke (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:389:12)\n    at phaseInvoke (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:654:9)\n    at runHandler (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/loopback-phase/lib/phase.js:135:5)\n    at iterate (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)\n    at Object.async.eachSeries (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)\n    at runHandlers (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/loopback-phase/lib/phase.js:144:13)\n    at iterate (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)\n    at /Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:157:25\n    at /Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25\n    at execStack (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:493:7)\n    at RemoteObjects.execHooks (/Users/candy/loopback/triage/postgres/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:497:10)"
  }
}
```
Could someone share a sample repo that reproduces this issue? Also, which version of juggler are you using?

**Comment by vegham** [comment]
Crashes with: {"where":{"geo":{"near":[100,100]}}}

Does not crash with memory database, but does with postgresql which I'm normally using. Seems like the difference happens somewhere in loopback-datasource-juggler/lib/dao.js

  "dependencies": {
    "loopback": "3.6.0",
    "loopback-boot": "2.24.0",
    "loopback-component-explorer": "4.0.0",
    "loopback-connector-postgresql": "3.0.0",
    "loopback-datasource-juggler": "3.5.0",
    "strong-error-handler": "1.0.1",
  },
  "engines": {
    "node": "6.0.0"
  }

**Comment by alzab** [comment]
Just to confirm - to this date I've also noticed this happens with *any* user-defined datatype where an exception is thrown on constructing it.  The outcome is an error 500 rather than 422 - it would be much nicer if the exception was handled rather than letting it trigger an "internal server error" response. Surely the exception should be handled somewhere in the call stack, to treat it as a form of validation?
@raymondfeng is this issue known in any more general sense?
