### ISSUE TITLE
attacked formatting

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback-datasource-juggler#1082]
juggler failed from accepted invalid json. It is listed as below:
```
8:43:23.645062+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:98
2016-09-07T08:43:23.645073+00:00 app[web.1]:     process.nextTick(function() { throw err; });
2016-09-07T08:43:23.645078+00:00 app[web.1]:                                   ^
2016-09-07T08:43:23.645079+00:00 app[web.1]: 
2016-09-07T08:43:23.645079+00:00 app[web.1]: Error: could not create List from JSON string: ""
2016-09-07T08:43:23.645081+00:00 app[web.1]:     at new List (/app/node_modules/loopback-datasource-juggler/lib/list.js:21:17)
2016-09-07T08:43:23.645081+00:00 app[web.1]:     at List (/app/node_modules/loopback-datasource-juggler/lib/list.js:14:12)
2016-09-07T08:43:23.645082+00:00 app[web.1]:     at ModelConstructor.Object.defineProperty.set [as path] (/app/node_modules/loopback-datasource-juggler/lib/model-builder.js:462:43)
2016-09-07T08:43:23.645083+00:00 app[web.1]:     at ModelConstructor.ModelBaseClass._initProperties (/app/node_modules/loopback-datasource-juggler/lib/model.js:192:17)
2016-09-07T08:43:23.645084+00:00 app[web.1]:     at ModelConstructor.ModelBaseClass (/app/node_modules/loopback-datasource-juggler/lib/model.js:54:8)
2016-09-07T08:43:23.645085+00:00 app[web.1]:     at ModelConstructor (/app/node_modules/loopback-datasource-juggler/lib/model-builder.js:183:22)
2016-09-07T08:43:23.645086+00:00 app[web.1]:     at new ModelConstructor (/app/node_modules/loopback-datasource-juggler/lib/model-builder.js:183:22)
2016-09-07T08:43:23.645086+00:00 app[web.1]:     at ModelConstructor.ModelBaseClass._initProperties (/app/node_modules/loopback-datasource-juggler/lib/model.js:333:28)
2016-09-07T08:43:23.645087+00:00 app[web.1]:     at ModelConstructor.ModelBaseClass (/app/node_modules/loopback-datasource-juggler/lib/model.js:54:8)
2016-09-07T08:43:23.645088+00:00 app[web.1]:     at ModelConstructor (/app/node_modules/loopback-datasource-juggler/lib/model-builder.js:183:22)
2016-09-07T08:43:23.645088+00:00 app[web.1]:     at ModelConstructor (/app/node_modules/loopback-datasource-juggler/lib/model-builder.js:183:22)
2016-09-07T08:43:23.645089+00:00 app[web.1]:     at new ModelConstructor (/app/node_modules/loopback-datasource-juggler/lib/model-builder.js:183:22)
2016-09-07T08:43:23.645090+00:00 app[web.1]:     at buildResult (/app/node_modules/loopback-datasource-juggler/lib/dao.js:1696:21)
2016-09-07T08:43:23.645090+00:00 app[web.1]:     at /app/node_modules/loopback-datasource-juggler/lib/dao.js:1743:13
2016-09-07T08:43:23.645091+00:00 app[web.1]:     at doNotify (/app/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
2016-09-07T08:43:23.645092+00:00 app[web.1]:     at doNotify (/app/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
```
Does it have anything to do with #148 ?

**Comment by jannyHou** [comment]
Thank you @jjhesk you are right and this is the issue to keep track of this bug:
https://github.com/strongloop/loopback-datasource-juggler/issues/111

I am closing this one to keep git issues clean. Let's move discussion there to get more people involved.

Thanks for understanding!
