### ISSUE TITLE
Support Node.js 7.x

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#1166]
`npm test` is failing on Node v7.1.0 right now:

```
  1) ModelBuilder processing json files allows model extension:
      AssertionError: 6 == 7
      + expected - actual
      -6
      +7
      
      at Context.<anonymous> (test/loopback-dl.test.js:1748:12)
```

We need to identify & fix the problem and add Node v7 to `.travis.yml`.

**Comment by bajtos** [comment]
I consider this as a major bug because most likely these failures are caused by existing errors that haven't been surfaced yet.

I see this as being similar to adding `use strict` and then discovering that certain tests suddenly start failing. (Which is the case in juggler too, there are several files that don't have "use strict" at the top, because such change fails many tests.)

**Comment by superkhau** [comment]
While on the topic, is this time to add Node 7 on CI?

**Comment by bajtos** [comment]
> While on the topic, is this time to add Node 7 on CI?

That's off topic, please discuss this elsewhere. (Perhaps open a new issue in one of our internal boards?)

**Comment by bajtos** [comment]
Probably related: when applying browserify + babel in loopback's Karma tests, the tests fail in recent Chrome with the following error:

```
Chrome 56.0.2924 (Mac OS X 10.12.2) Replication / Change APIs change detection detects "findOrCreate" FAILED
	TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
	    at DataSource.ready (/var/folders/ht/v2sc3fbn5m77w03kybtbf6h40000gp/T/node_modules/loopback-datasource-juggler/lib/datasource.js:2100:20 <- /var/folders/ht/v2sc3fbn5m77w03kybtbf6h40000gp/T/49bf708c0bdc21308704a570ddfaba8f.browserify:83659:20)
	    at stillConnecting (/var/folders/ht/v2sc3fbn5m77w03kybtbf6h40000gp/T/node_modules/loopback-datasource-juggler/lib/dao.js:411:22 <- /var/folders/ht/v2sc3fbn5m77w03kybtbf6h40000gp/T/49bf708c0bdc21308704a570ddfaba8f.browserify:78712:23)
	    at Function.findOrCreate (/var/folders/ht/v2sc3fbn5m77w03kybtbf6h40000gp/T/node_modules/loopback-datasource-juggler/lib/dao.js:993:26 <- /var/folders/ht/v2sc3fbn5m77w03kybtbf6h40000gp/T/49bf708c0bdc21308704a570ddfaba8f.browserify:79295:27)
   (...)
```

Link to the source code line causing the problem: https://github.com/strongloop/loopback-datasource-juggler/blob/b781dae3398b94858833fb4afa2d419ae2ea9a94/lib/datasource.js#L2100-L2101

**Comment by dhmlau** [comment]
@ssh24 , I think you've fixed the original problem in https://github.com/strongloop-internal/scrum-apex/issues/209.  Please take a look at the discussion in this issue to see if we've taken care of it already.  Thanks!

**Comment by ssh24** [comment]
Test case fixed on https://github.com/strongloop/loopback-datasource-juggler/pull/1392. Closing the story.
