### ISSUE TITLE
Cannot read property '_receiver' of null

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback-datasource-juggler#1202]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I have some tests which ran fine on 2.53.0. One of them fails on 2.53.1  
I have a model Task with some related models. In a before delete hook I delete the related models:  

````
function deleteRelations(ctx, next)
	{
		// only allow delete if we have no results for this task
		Task.find({where: ctx.where, include: 'results'}, function(err, tasks) {
			if (err) {
				return next(err);
			}

			if (tasks.length === 0) {
				return next();
			}

			var m = Task.app.models,
				TaskEduContent = m.TaskEduContent,
				TaskGroup = m.TaskGroup,
				TaskStudent = m.TaskStudent,
				taskIds = [];
				tasks.forEach(function(task) {
					// exclude tasks with results
					if (task.toJSON().results.length === 0) {
						taskIds.push(task.id);
					}
				});
			// check if we can delete all selected tasks
			if (taskIds.length !== tasks.length) {
				var error = new Error('task_has results');
				error.code = 'TASK_HAS_RESULTS';
				error.statusCode = 403;
				return next(err);
			}

			var q = [
					// delete all linked eduContent
					async.apply(TaskEduContent.destroyAll.bind(TaskEduContent), {taskId: {inq: taskIds}}),
					// delete all linked groups and students
					async.apply(TaskGroup.destroyAll.bind(TaskGroup), {taskId: {inq: taskIds}}),
					async.apply(TaskStudent.destroyAll.bind(TaskStudent), {taskId: {inq: taskIds}})
				];
			// unlink bundles
			tasks.forEach(function(task) {
				var cmd = async.apply(task.bundles.destroyAll);
				q.push(cmd);
			});

			async.parallel(q, function(err/*, result*/) {
				if (err) {
					return next(err);
				}

				next();
			});
		});
	}
````
### Expected result
Related models should be deleted first

### Actual result (if bug)
````
Uncaught TypeError: Cannot read property '_receiver' of null
      at destroyAll (node_modules/loopback-datasource-juggler/lib/scope.js:373:50)
      at node_modules/async/lib/async.js:760:23
      at node_modules/async/lib/async.js:166:37
      at node_modules/async/lib/async.js:718:13
      at async.forEachOf.async.eachOf (node_modules/async/lib/async.js:233:13)
      at _parallel (node_modules/async/lib/async.js:717:9)
      at Object.async.parallel (node_modules/async/lib/async.js:731:9)
      at common/models/task.js:73:10
      at node_modules/loopback-datasource-juggler/lib/dao.js:1944:11
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
      at done (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:393:21
      at node_modules/loopback-datasource-juggler/lib/dao.js:1921:17
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at node_modules/loopback-datasource-juggler/lib/dao.js:1918:21
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:391:17
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13
      at _each (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)
      at async.each (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:156:9)
      at _asyncMap (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:390:13)
      at Object.map (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:361:23)
      at allCb (node_modules/loopback-datasource-juggler/lib/dao.js:1872:15)
      at node_modules/loopback-datasource-juggler/lib/include.js:182:11
      at done (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
      at targetFetchHandler (node_modules/loopback-datasource-juggler/lib/include.js:518:9)
      at node_modules/loopback-datasource-juggler/lib/dao.js:1944:11
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
      at async.each (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:153:20)
      at _asyncMap (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:390:13)
      at Object.map (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:361:23)
      at allCb (node_modules/loopback-datasource-juggler/lib/dao.js:1872:15)
      at node_modules/loopback-datasource-juggler/lib/connectors/memory.js:472:7
      at node_modules/async-listener/glue.js:188:31
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
````

### Additional information (Node.js version, LoopBack version, etc)
node v6.9.2
loopback@2.36.0
loopback-datasource-juggler@2.53.1

**Comment by ernie58** [comment]
Anyone?

**Comment by ernie58** [comment]
ping ^^^^

**Comment by loay** [comment]
Hi @ernie58 
Can you please provide a sample repo so I can reproduce and debug the issue? Thanks
http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
