### ISSUE TITLE
Geo query fails with null property

### ISSUE THREAD

**Issue by garrows** [strongloop/loopback-datasource-juggler#1332]
Since updating to v3.5.0 I started encountering this crash. Code was introduced here https://github.com/strongloop/loopback-datasource-juggler/commit/64f64caaff70898281b09d8469db4e7a89fa160f#diff-b367a815d81f15531e0d0553ea8aaa5aR28

I dont have time right now to give you a proper reproduction case but hopefully this will help you and others encountering the problem.

For now I have rolled back to `loopback-datasource-juggler@3.4.1`

```
TypeError: Cannot read property 'hasOwnProperty' of null
    at /Users/glen/api/node_modules/loopback-datasource-juggler/lib/geo.js:28:30
    at Array.forEach (native)
    at nearSearch (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/geo.js:21:25)
    at Object.nearFilter (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/geo.js:44:3)
    at Function.find (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:1891:27)
    at /Users/glen/api/node_modules/loopback/common/models/user.js:322:15
    at notifySingleObserver (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:104:22)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:3025:16
    at replenish (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:881:17)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:885:9
    at eachLimit$1 (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:3114:22)
    at Object.<anonymous> (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:917:16)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:101:11)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:2782:15
    at /Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:112:23
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at replenish (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:876:25)
    at iterateeCallback (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:866:17)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
    at Model.observe (/Users/glen/api/node_modules/@console/loopback-soft-delete-mixin/common/mixins/soft-delete.js:20:5)
    at notifySingleObserver (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:104:22)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:3025:16
    at replenish (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:881:17)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:885:9
    at eachLimit$1 (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:3114:22)
    at Object.<anonymous> (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:917:16)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:101:11)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:112:23
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at replenish (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:876:25)
    at iterateeCallback (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:866:17)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
    at normalizeEmailCase (/Users/glen/api/node_modules/loopback/common/models/user.js:969:5)
    at notifySingleObserver (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:104:22)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:3025:16
    at replenish (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:881:17)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:885:9
    at eachLimit$1 (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:3114:22)
    at Object.<anonymous> (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:917:16)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:101:11)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at ModelConstructor.DataAccessObject.remove.DataAccessObject.delete.DataAccessObject.destroy (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:2773:13)
    at module.exports (/Users/glen/api/[redacted]/delete.js:2:31)
    at Layer.handle [as handle_request] (/Users/glen/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/glen/api/node_modules/express/lib/router/route.js:137:13)
    at self.service.getUserById (/Users/glen/api/[redacted]:5:5)
    at core.routeLoader.getRoles (/Users/glen/api/[redacted]:19:7)
    at Object.getRoles (/Users/glen/api/[redacted]:371:9)
    at Agent.findById (/Users/glen/api/[redacted]:13:22)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:2142:5
    at /Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:2070:9
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:935:13)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1009:13
    at buildResult (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:2036:11)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:2050:13
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at withNotify (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:2048:17)
    at /Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:1989:11
    at /Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1007:9
    at eachOfArrayLike (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:940:9)
    at eachOf (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:990:5)
    at _asyncMap (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1005:5)
    at Object.map (/Users/glen/api/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:995:16)
    at allCb (/Users/glen/api/node_modules/loopback-datasource-juggler/lib/dao.js:1984:13)
    at /Users/glen/api/node_modules/loopback-connector-mongodb/lib/mongodb.js:1009:9
    at handleCallback (/Users/glen/api/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/glen/api/node_modules/mongodb/lib/cursor.js:860:16
    at handleCallback (/Users/glen/api/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorDeadAndNotified (/Users/glen/api/node_modules/mongodb-core/lib/cursor.js:505:3)
    at nextFunction (/Users/glen/api/node_modules/mongodb-core/lib/cursor.js:599:12)
    at Cursor.next [as _next] (/Users/glen/api/node_modules/mongodb-core/lib/cursor.js:692:3)
    at fetchDocs (/Users/glen/api/node_modules/mongodb/lib/cursor.js:856:10)
    at /Users/glen/api/node_modules/mongodb/lib/cursor.js:879:7
    at handleCallback (/Users/glen/api/node_modules/mongodb-core/lib/cursor.js:171:5)
    at nextFunction (/Users/glen/api/node_modules/mongodb-core/lib/cursor.js:682:5)
    at /Users/glen/api/node_modules/mongodb-core/lib/cursor.js:593:7
    at queryCallback (/Users/glen/api/node_modules/mongodb-core/lib/cursor.js:232:18)
    at /Users/glen/api/node_modules/mongodb-core/lib/connection/pool.js:461:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by dhmlau** [comment]
Seems like it's related to the PR https://github.com/strongloop/loopback-datasource-juggler/pull/1314

**Comment by ebarault** [comment]
cc: @ssh24

**Comment by paulussup** [comment]
```Model.find({where: {field: null}})```

**Comment by jdhrivas** [comment]
@kjdelisle how soon can we expect a new release 3.5.1? It looks like updating to loopback 3.8 is forcing juggler@3.5. I'll looking into rolling back in the meantime.

**Comment by kjdelisle** [comment]
@jdhrivas loopback-datasource-juggler@3.6.0 is out now.

When I look at the [loopback@master's package.json](https://github.com/strongloop/loopback/blob/master/package.json) , I see the dep pinned to `^3.0.0`, so I don't think anything should be forcing that package version...

**Comment by jdhrivas** [comment]
@kjdelisle you are correct, my own package.json is the problem. I'll update to juggler@3.6.0 

Btw. Thank you for your work.
