### ISSUE TITLE
ReferencesMany ignores properties of foreignKey breaking SQL columnName mapping

### ISSUE THREAD

**Issue by pastcompute** [strongloop/loopback-datasource-juggler#1346]
# Description/Steps to reproduce

1. Create a `referencesMany` relation in the model JSON:
```
  "relations": {
    "otherPeople": {
      "type": "referencesMany",
      "model": "People",
      "foreignKey": "otherPeopleIds"
    }
```
2. Add a matching property for the foreign key to map to postgresql or any other SQL connector `columnName`. This approach has been confirmed to work for `belongsTo`
```
  "properties": {
    "otherPeopleIds": {
      "type": ["number"],
      "postgresql": {
        "columnName": "the_people_ids",
      }
    }
  }
```
3. The `columnName` mapping is ignored causing backtrace
```
Unhandled error for request GET /SomeModel: error: column "otherPeopleIds" does not exist
    at Connection.parseE (/home/andrew/DEVELOP/Platfarm/grow4-server-loopback/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/home/andrew/DEVELOP/Platfarm/grow4-server-loopback/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/home/andrew/DEVELOP/Platfarm/grow4-server-loopback/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```
With debug on you can see the incorrect column name in the SQL.

 This is confirmed by adding the following boot js code:
```
module.exports = function(app) {
  debug('Model  definition=%j', app.models.SomeModel.dataSource.getModelDefinition('SomeModel'));
  debug('Model  columnNames=%j', app.models.SomeModel.dataSource.columnNames('SomeModel'));
```
In the output can be seen 
```
definition={"name":"SomeModel","properties":{"otherPeopleIds":{"type":["Number"],"default":"default"}
```
If as a test I remove the relation, I get the correct array definition including postgres.

I found where the property gets created by ReferencesMany, inside relation-definition.js on around line 3040
```
  modelFrom.dataSource.defineProperty(modelFrom.modelName, fk, {
    type: [idType], default: function() { return []; },
  });
```

I also looked at belongsTo but it does things differently so I cant work out what needs to be added to get the property to merge with the other property

# Expected result

# Additional information

```
linux x64 7.4.0
├── loopback@3.5.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@4.2.0
├── loopback-connector-postgresql@2.7.0
├── loopback-datasource-juggler@3.4.1
├── loopback-ds-readonly-mixin@1.0.1
```

**Comment by pastcompute** [comment]
The exact same bug is in the code for EmbedsMany relation definition
