### ISSUE TITLE
prototype$updateAttributes not working as expected

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#1400]
_From @ilianaza on March 16, 2015 23:34_

I've upgraded different loopback packages:

```
"loopback": "^2.13.0"  ->  "loopback": "^2.14.0"
"loopback-component-storage": "~1.3.0"  ->  "loopback-component-storage": "~1.3.1",
"loopback-datasource-juggler": "^2.18.1"  ->  "loopback-datasource-juggler": "^2.19.2",
```

This upgrade changed the way the prototype$updateAttributes method worked. Before I was able to update an attribute of an instance this way:

``` javascript
course.name = "New name";
Course.prototype$updateAttributes(course) ...
```

But now I get the following error:

``` json
{  
  "error":{  
    "name":"Error",
    "status":400,
    "message":"id property value cannot be updated: id",
    "statusCode":400,
    "stack":"Error: id property value cannot be updated: id    
    at ModelConstructor.updateAttributes (.../node_modules/loopback-datasource-juggler/lib/dao.js:1912:17)    
    at SharedMethod.invoke (.../node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:252:25)    
    at HttpContext.invoke (.../node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:286:12)    
    at .../node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:550:9    
    at execStack (.../node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:403:7)    
    at .../node_modules/loopback/lib/application.js:326:13    
    at .../node_modules/loopback/lib/model.js:299:5    
    at .../node_modules/loopback/common/models/acl.js:441:23    
    at .../node_modules/async/lib/async.js:254:17    
    at done (.../node_modules/async/lib/async.js:135:19)"
  }
}
```

The only way I'm able to update instance attributes now is:

``` javascript
course.name = "New name";
Course.prototype$updateAttributes({ id: course.id }, { name: "New name" }) ...
```

My model has 20 attributes and I don't want to list them all in the 2nd parameter of the $updateAttributes call. If I pass an instance as a 2nd parameter then I get "400" error listed above. 

Is there any other way to update multiple or all attributes of an instance without listing them one by one? Can't find anything in docs on this and need your guidance.

_Copied from original issue: strongloop/loopback-sdk-angular#134_

**Comment by bajtos** [comment]
_From @raymondfeng on March 16, 2015 23:38_

The behavior was introduced by https://github.com/strongloop/loopback-datasource-juggler/pull/508. It fixes a security hole that potentially allows non-owner to mess up with the id. You can remove the id before it's sent to the backend.

BTW, do you use mongodb?

**Comment by bajtos** [comment]
_From @ilianaza on March 17, 2015 0:36_

Yes, I use mongodb.

**Comment by bajtos** [comment]
_From @ilianaza on March 17, 2015 2:33_

Does that somehow affect the way $updateAttributes method should be called?

**Comment by bajtos** [comment]
_From @raymondfeng on March 17, 2015 6:3_

Yes, the `id` property cannot be set in the `data` argument. We also allow the `id` if it is the same as the instance id. In the case of MongoDB, the id type is ObjectId, which doesn't always satisfy `===`.

**Comment by bajtos** [comment]
@raymondfeng Can we please fix MongoDB connector so that it accepts `updateAttributes` requests that include the `id` property but don't change the value?

**Comment by bajtos** [comment]
_From @richardpringle on May 11, 2016 13:34_

@bajtos, do you know if this issue was resolved? I don't see any PR attached to this issue.

**Comment by bajtos** [comment]
@richardpringle I think we still need to fix  loopback-datasource-juggler, loopback-connector-mongodb or both. This may be related to the problem with ObjectID coercion for which we don't have a generic solution yet.

**Comment by bajtos** [comment]
BTW while fixing this in `updateAttributes`, we should fix it in `replaceById` too.

**Comment by bajtos** [comment]
@kjdelisle can somebody from your team take a look? IIUC, the problem is that `updateAttributes` fails if the data payload contains `id` (primary key) property, even if the id value is the same as the id of the resource to be updated.
