### ISSUE TITLE
Newly added relation test causes cassandra connector CI to fail

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-datasource-juggler#1446]
Cassandra connector CI is failing because
```
imported features relations hasMany through find over related model with options should find be filtered from option:

      Uncaught AssertionError: expected Array [ 'z:test', 'a:test' ] to equal Array [ 'a:test', 'z:test' ] (at '0', A has 'z:test' and B has 'a:test')
      + expected - actual

       [
      +  "a:test"
         "z:test"
      -  "a:test"
       ]
      
      at Assertion.fail (node_modules/should/cjs/should.js:258:17)
      at Assertion.value (node_modules/should/cjs/should.js:335:19)
      at node_modules/loopback-datasource-juggler/test/relations.test.js:959:27
```
I think it is related to this PR:
https://github.com/strongloop/loopback-datasource-juggler/pull/1426

cc @ssh24

**Comment by ssh24** [comment]
Issue fixed with #1449
