### ISSUE TITLE
probably malformed query string crashes app

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback-datasource-juggler#1524]
# Description/Steps to reproduce

Using superagent, I'm making an HTTP request to fetch a related model and filter its props.
```
Client hasMany Child
Child hasMany Job
```
I am fetching the childs of a Client, and the jobs of this child with this request
```
GET Client/1/childs
```
and using this filter I only keep the `status` prop of jobs
```
{
    filter: {
      include: {
        relation: 'jobs',
        scope: {
          fields: ['status']
        }
      }
    }
  }
}
```
After performing the request, server crashes immediately.

```
var keyToString = function(key) { return key.toString(); };
                                             ^

TypeError: Cannot read property 'toString' of undefined
   at keyToString (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\include_utils.js:68:47)
   at Object.get (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\include_utils.js:78:28)
   at Object.buildOneToManyIdentityMapWithOrigKeys (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\include_utils.js:35:23)
   at targetFetchHandler (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\include.js:512:41)
   at C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\dao.js:1985:11
   at C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:396:17
   at done (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:167:19)
   at C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:40:16
   at C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:393:21
   at C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\dao.js:1962:17
   at doNotify (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\observer.js:99:49)
   at doNotify (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\observer.js:99:49)
   at doNotify (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\observer.js:99:49)
   at doNotify (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\observer.js:99:49)
   at Function.ObserverMixin._notifyBaseObservers (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\observer.js:122:5)
   at Function.ObserverMixin.notifyObserversOf (C:\Users\*****\Gitlab\###########\node_modules\loopback-datasource-juggler\lib\observer.js:97:8)
```

# Expected results

I'm not sure superagent supports nested objects for query string, but in any case a malformed query string should not crash the server.

# Additional information

```
node -e "console.log(process.platform, process.arch, process.versions.node)"
win32 x64 6.11.0

npm ls --depth=0
+-- async@2.4.1
+-- bull@3.0.0-rc.3
+-- compression@1.6.2
+-- cors@2.8.3
+-- debug@3.0.1
+-- google-auto-auth@0.7.0
+-- helmet@1.3.0
+-- ioredis@3.1.1
+-- lodash@4.17.4
+-- loopback@2.39.0
+-- loopback-boot@2.24.1
+-- loopback-component-explorer@2.7.0
+-- loopback-component-storage@3.3.1
+-- loopback-datasource-juggler@2.54.2
+-- moment@2.18.1
+-- rrule@2.2.0
+-- serve-favicon@2.4.3
+-- sinon@2.4.1
+-- sinon-chai@2.13.0
+-- strong-error-handler@2.1.0
+-- superagent@3.5.2
+-- uuid@3.1.0
`-- validator@9.1.1
```

**Comment by dhmlau** [comment]
@strongloop/sq-lb-apex  PTAL

**Comment by jannyHou** [comment]
Hi @Overdrivr I created a sample app according to your description, but don't see the error:
You can 

- git clone https://github.com/jannyhou/loopback-sandbox/tree/1524
- `npm i`
- `node .`
- In explorer, try endpoint:
  - GET /Clients/{id}/children 
  - provide id = 1
  - provide filter `{"include": {"relation": "jobs", "scope": {"fields": ["status"]}}}`

I already generated some sample data in `mydata.json` and I can get the result:

```
[
  {
    "name": "child1",
    "id": 1,
    "clientId": 1,
    "jobs": [
      {
        "status": "status1",
        "childId": 1
      }
    ]
  }
]
```

To help you solve the problem, can you fork my repo(branch #1524) and modify the app to contain the error code and provide me the steps to run it? Thanks.

Or feel free to fork https://github.com/strongloop/loopback-sandbox to build your app from scratch

**Comment by Overdrivr** [comment]
I noticed that the issue can only be reproduced using superagent. I'm
currently in vacation but i will provide exact code to reproduce when i
come back (sorry about it, i should have provided it in the first place).

**Comment by Overdrivr** [comment]
@jannyHou Sorry about the delay in response, I did not see your previous message. Here is a sample script that reproduces the error with your sample repository, and latest version of superagent.

```
var request = require('superagent');

request
  .get('localhost:3000/api/Clients/1/children')
  .query({
    filter: {
      include: {
        relation: 'jobs',
        scope: {
          fields: ['status']
        }
      }
    }
  })
  .end(function(err, res) {
    console.log(err);
    console.log(res.body);
  });
```
