### ISSUE TITLE
persist hook returning error is ignored by persistedModel.updateAttributes(data, callback)

### ISSUE THREAD

**Issue by icezjy** [strongloop/loopback-datasource-juggler#1528]
# Description/Steps to reproduce

I have a model, named 'person', where I implemented a persist hook to avoid reserved word for field `address`.

However I've found that when using Model.updateAttributes(), if the persist hook has an error, it's ignored and not returned to callback of persisitedModel.updateAttributes, it will proceed and write to the db.

Example code to call next with an error:

```
module.exports = function (app, cb) {
  app.models.person.observe('persist', (ctx, next) => {
    if (ctx.currentInstance && ctx.currentInstance.address === 'Mars') {
      next(new Error('Invalid address'));
    } else {
      next()
    }
  });
  cb();
};
```

Testing code:

```
  it('Verify person model', () => new Promise((resolve, reject) => {
    const john = {
      last_name: "Smith",
      first_name: "John",
      address: "Building Ring",
      phone: "12345678"
    }

    app.models.person.create(john, (err, instance) => {
      if (err) {
         reject(err);
      } else {
        instance.updateAttributes({address: "Mars"}, (error, updatedInstance) => {
          expect(error).to.be.not.null;
          resolve();
        })
      }
    });
  }));
```
# Link to reproduction sandbox

Please load project https://github.com/icezjy/testloopback and run below command to reproduce:

```
cd persist
npm install
npm test
```

# Expected result

Test case should complete successfully, as Mars is a reserved work and rejected by persist hook. But case fails with:

```
> persist@1.0.0 test /Users/icecream/testloopback/persist
> cross-env node_modules/.bin/babel-node node_modules/mocha/bin/_mocha tests/**/*[sS]pec.js --exec babel-node



  common/models/person
    1) Verify person model


  0 passing (434ms)
  1 failing

  1) common/models/person Verify person model:
     Uncaught AssertionError: expected null not to be null
      at instance.updateAttributes (tests/common/models/person.spec.js:24:11)
      at node_modules/loopback-datasource-juggler/lib/dao.js:3313:23
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at ModelConstructor.<anonymous> (node_modules/loopback-datasource-juggler/lib/dao.js:3312:27)
      at ModelConstructor.next (node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)
      at ModelConstructor.<anonymous> (node_modules/loopback-datasource-juggler/lib/dao.js:3302:28)
      at ModelConstructor.next (node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)
      at node_modules/loopback-datasource-juggler/lib/dao.js:3301:22
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at updateAttributesCallback (node_modules/loopback-datasource-juggler/lib/dao.js:3289:21)
      at node_modules/loopback-datasource-juggler/lib/connectors/memory.js:367:5
      at node_modules/loopback-datasource-juggler/lib/connectors/memory.js:225:19
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)



npm ERR! Test failed.  See above for more details.
icecreamdeimac:persist icecream$ pwd
```

# Additional information

In https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js, see that when persist hook return `err`, `err` is ignored by dao. 

```
            var ctx = {
              Model: Model,
              where: byIdQuery(Model, getIdValue(Model, inst)).where,
              data: context.data,
              currentInstance: inst,
              isNewInstance: false,
              hookState: hookState,
              options: options,
            };
            Model.notifyObserversOf('persist', ctx, function(err) {
              invokeConnectorMethod(connector, 'updateAttributes', Model,
                [getIdValue(Model, inst), Model._forDB(context.data)],
                options, updateAttributesCallback);
            });
```

Consider to add `if (err) return cb(err);` before `invokeConnectorMethod`.

**Comment by icezjy** [comment]
any comment to this issue? it is a blocker for our product.
