### ISSUE TITLE
SyntaxError: Invalid regular expression: /"("/: Unterminated group

### ISSUE THREAD

**Issue by kalpana-ideas2it** [strongloop/loopback-datasource-juggler#1570]
I have autocompleted functionality in my application When I start a search with '(' i get the below  exception 

my code 
```
  const searchProfiles = (filter, responseCb) => {
    console.log("...filter.",filter);
    filter.searchTerm = filter.searchTerm || '';
    const where = filter.where;
    where.name = { regexp: '/' + filter.searchTerm + '/i' };
    let query = {
      where,
      skip: filter.skip,
      limit: filter.limit,
      order: filter.order
    }
    console.log(query);
     text.find(query, (err, profiles) => {
      responseCb(err, query.where, profiles);
    });
  };

```

Exception

```
SyntaxError: Invalid regular expression: /"("/: Unterminated group
    at RegExp (native)
    at Object.toRegExp (/home/ubuntu/projects//node_modules/loopback-datasource-juggler/lib/utils.js:614:10)
    at Function.DataAccessObject._coerce (/home/ubuntu/projects/ita/ita-services/node_modules/loopback-datasource-juggler/lib/dao.js:1769:27)
    at Function.DataAccessObject._normalize (/home/ubuntu/projects/node_modules/loopback-datasource-juggler/lib/dao.js:1580:8)
    at Function.find (/home/ubuntu/projects/node_modules/loopback-datasource-juggler/lib/dao.js:1927:10)
```

**Comment by dhmlau** [comment]
@jannyHou , do you know if we're supposed to escape the special characters?
