### ISSUE TITLE
Version >=3.25.0 regression for hasOne relationship and hidden property

### ISSUE THREAD

**Issue by elv1s** [strongloop/loopback-datasource-juggler#1664]
# Description
In `loopback-datasource-juggler@3.25.0` only 1 instance of an object with a `hasOne` relationship can be created for all items in a collection if the related object has hidden properties.

# Steps to reproduce

In the https://github.com/strongloop/loopback-example-relations repository add a "widget" model and ***add the foreign key to the "hidden" array.***

widget.json
```json
{
  "name": "Widget",
  "plural": "widgets",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "hidden": [
    "customerId"
  ],
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

model-config.json
```json
"Widget": {
    "dataSource": "db",
    "public": true
  },
```

Add a hasOne relation from the Customer to the Widget

customer.json
```json
"relations": {
    "widget": {
      "type": "hasOne",
      "model": "Widget",
      "foreignKey": "customerId",
      "primaryKey": "id",
      "options": {
        "validate": true,
        "forceId": true,
        "nestRemoting": true
      }
    }
    ...
}
```

Post widgets to 2 separate customers
```
curl http://localhost:3000/api/Customers/1/widget -H "content-type: application/json" -d '{"name": "widget1"}' 
{
  "name": "widget1",
  "id": 1
}

curl http://localhost:3000/api/Customers/2/widget -H "content-type: application/json" -d '{"name": "widget2"}' 
{"error":{"statusCode":500,"message":"Internal Server Error"}}
```

# Expected result

You should be able to create 1 widget for every customer.

# Additional information
The error is happening here: https://github.com/strongloop/loopback-datasource-juggler/blob/v3.25.0/lib/utils.js#L344

`prohibitedKeys` is assumed to be an array, but in certain cases is an object containing hidden fields.

The errors are slightly different between versions of the juggler

<details><summary>3.25.0 Error</summary>

```
Potential security alert: hidden/protected properties ["customerId"] are used in query.
Unhandled error for request POST /Customers/2/widget: TypeError: prohibitedKeys.indexOf is not a function
    at Object.<anonymous> (/home/joe/publicCode/loopback-example-relations/node_modules/loopback-datasource-juggler/lib/utils.js:344:42)
    at walker (/home/joe/publicCode/loopback-example-relations/node_modules/traverse/index.js:190:22)
    at walk (/home/joe/publicCode/loopback-example-relations/node_modules/traverse/index.js:226:7)
    at Traverse.forEach (/home/joe/publicCode/loopback-example-relations/node_modules/traverse/index.js:50:18)
    at sanitizeQuery (/home/joe/publicCode/loopback-example-relations/node_modules/loopback-datasource-juggler/lib/utils.js:329:34)
    at Function.DataAccessObject._sanitize (/home/joe/publicCode/loopback-example-relations/node_modules/loopback-datasource-juggler/lib/dao.js:1675:10)
    at Function.DataAccessObject._normalize (/home/joe/publicCode/loopback-example-relations/node_modules/loopback-datasource-juggler/lib/dao.js:1584:17)
    at Function.findOrCreate (/home/joe/publicCode/loopback-example-relations/node_modules/loopback-datasource-juggler/lib/dao.js:1195:12)
    at HasOne.create (/home/joe/publicCode/loopback-example-relations/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1816:11)
    at Customer.modelFrom.(anonymous function) [as __create__widget] (/home/joe/publicCode/loopback-example-relations/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1767:7)
    at SharedMethod.invoke (/home/joe/publicCode/loopback-example-relations/node_modules/strong-remoting/lib/shared-method.js:270:25)
    at HttpContext.invoke (/home/joe/publicCode/loopback-example-relations/node_modules/strong-remoting/lib/http-context.js:297:12)
    at phaseInvoke (/home/joe/publicCode/loopback-example-relations/node_modules/strong-remoting/lib/remote-objects.js:695:9)
    at runHandler (/home/joe/publicCode/loopback-example-relations/node_modules/loopback-phase/lib/phase.js:135:5)
    at /home/joe/publicCode/loopback-example-relations/node_modules/async/dist/async.js:3110:16
    at replenish (/home/joe/publicCode/loopback-example-relations/node_modules/async/dist/async.js:1011:17)
```

</details>

<details><summary>3.27.0 Error</summary>

```
Potential security alert: hidden/protected properties ["customerId"] are used in query.
Unhandled error for request POST /Customers/2/widget: Error: HasOne relation cannot create more than one instance of Widget
    at /home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1826:18
    at /home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:1164:13
    at doNotify (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at findOrCreateCallback (/home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:1134:13)
    at /home/joe/publicCode/loopback-example-relations/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:344:7
```

</details>

### system info
```
node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 8.12.0
```
```
npm ls --prod --depth 0 | grep loopback
loopback-example-relations@1.0.0 /home/joe/publicCode/loopback-example-relations
├── loopback@3.23.2
├── loopback-boot@2.27.1
├── loopback-component-explorer@5.4.0
├── loopback-connector-rest@3.4.1
├── loopback-datasource-juggler@3.25.0
```

**Comment by elv1s** [comment]
I noticed the related issue, but 3.25.1 still exhibits the failure but with a different error message. Same error message as 3.27.0 

```
Unhandled error for request POST /Customers/2/widget: Error: HasOne relation cannot create more than one instance of Widget
```

**Comment by raymondfeng** [comment]
Please verify with `loopback@3.24.0` and `loopback-datasource-juggler@3.28.0`

**Comment by elv1s** [comment]
This issue still happens with loopback@3.24.0 and loopback-datasource-juggler@3.28.0

What seems to be happening is that since the `customerId` is hidden in the `Widget` model, it is marking it as a prohibited key and stripping it from the `findOrCreate` query here: https://github.com/strongloop/loopback-datasource-juggler/blob/v3.28.0/lib/utils.js#L364

This will allow the first `findOrCreate` request for a `hasOne` relationship to pass, but the second request will find the original object since the `where customerId=2` is removed and find, but not create the second `hasOne` for a different `Customer`

```
npm ls --prod --depth 0 | grep loopback
loopback-example-relations@1.0.0 /home/joe/publicCode/loopback-example-relations
├── loopback@3.24.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@5.4.0
├── loopback-connector-rest@3.4.1
├── loopback-datasource-juggler@3.28.0
```

**Comment by raymondfeng** [comment]
Please configure `prohibitHiddenPropertiesInQuery: false` for the model or datasource setting to bypass the check. With loopback@3.24.0, such flag is set to `true` for remote method calls from REST.

You can also override `createOptionsFromRemotingContext` method for your model class, such as:
```js
MyModel. createOptionsFromRemotingContext = function(ctx) {
...
}
```

**Comment by elv1s** [comment]
Verified adding `"prohibitHiddenPropertiesInQuery": false` to the customer model fixes the issue.

customer.json
```
"prohibitHiddenPropertiesInQuery": false,
"relations": {
    "widget": {
      "type": "hasOne",
      "model": "Widget",
      "foreignKey": "customerId",
      "primaryKey": "id",
      "options": {
        "validate": true,
        "forceId": true,
        "nestRemoting": true
      }
    }
    ...
}
```

**Comment by dhmlau** [comment]
Thanks for verifying, @elv1s .
