### ISSUE TITLE
I can't see why 'FindById' calls 'Find'

### ISSUE THREAD

**Issue by Jethzabell** [strongloop/loopback-datasource-juggler#1689]
I can't see why 'FindById' calls 'Find'
If I **comment** the implementation of `Find`, Solution.findSolution `findById` works.
If I **uncomment** `Find`,  

`Solution.findSolution` calls Find and runs the implementation i coded in Find witch will cause an error.

Find

```javascript
Solution.on('dataSourceAttached', function() {
  var find = Solution.find;

  Solution.find = function (req, cb) {
    //console.log(req.protocol+"://"+req.headers.host);
    find.call(this, req, function(err, result) {
        console.log(result);
    });

      return cb(err, result);

    }); // close find.call()
  } // close Solution.find()
}); // close Solution.on()

//Remote method to find all solutions
Solution.remoteMethod('find',{
  description: 'Find solution instances from the data source',
  accepts: [
    {arg: 'req', type: 'object', http: {source: 'req'}}
  ],
  returns: {arg: 'solution', type: 'solution', root: true, description: "Success"},
  http: {
      path: '/',
      verb: 'get',
      status: 200,
      errorStatus: 405
  },
});
```

Find By ID
```javascript

// Remote method to find a solution through name

Solution.findSolution = function(name, req, cb){
    Solution.findById(name, function(err, sol){
      if(err || !sol){
        return cb(new Error("Solution not found"));
      } 
      return cb(null, sol);
    });
}


Solution.remoteMethod('findSolution',{
    description: 'Find solution instance by {{ name }} from the data source',
    accepts: [
        {arg: 'name', type: 'string', http: {source: 'path'}, required: true, description: 'Solution name'},
        {arg: 'req', type: 'object', http: {source: 'req'}}
    ],
    returns: {arg: 'solution', type: 'solution', root: true, description: "Success"},
    http: {
        path: '/:name',
        verb: 'get',
        status: 200,
        errorStatus: 404
    },
});
```

**Comment by Jethzabell** [comment]
Test Case:
When I GET /{name}

Throws

TypeError: Cannot read property 'host' of undefined
    at /Users/jethzabell/Desktop/GitLab/solution-catalog/common/models/solution.js:201:78
    at Array.forEach (<anonymous>)
    at /Users/jethzabell/Desktop/GitLab/solution-catalog/common/models/solution.js:200:14
....
....


Witch is on 'find' not findSolution(findById)

**Comment by jannyHou** [comment]
@Jethzabell Some connectors have the optimized `findById` method for `loopback-datasource-juggler` to invoke while some does not. And that's when `findById` eventually invokes `find` with a constraint filter.
