### ISSUE TITLE
Possible EventEmitter leak detected in datasource.js

### ISSUE THREAD

**Issue by lapellaniz** [strongloop/loopback-datasource-juggler#1691]
## Description/Steps to reproduce
Possible EventEmitter leak detected in datasource.js

- Using loopback v4 (core 1.1.3 and repository 1.1.1)
- Use a benchmark cli to send concurrent calls to test load a REST API using loopback/node.js
- The endpoint tested uses the loopback v4 controller/repository pattern with the loopback-connector-postgresql to send calls to AWS Redshift.
- 

## Observed result

- Sending 11 concurrent calls raises the warning `MaxListenersExceededWarning` and 2 log entries show up about the `connected` & `error` event listeners in the datasource.
- Once the warnings show up, they do not occur again unless you re-start the server and send the calls again.
- I tried to send just 10 concurrent calls the 1st time I started the server and then send more but I did not see the warnings. It seems to happen only if the first call to the server once it starts happens to be more than 10 concurrent calls.

## Expected result

- No warnings about a possible memory leak.

## Error

```javascript
(node:18196) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit
warning.js:18
    at _addListener (events.js:247:17)
    at RedshiftDataSource.addListener (events.js:263:10)
    at RedshiftDataSource.once (events.js:292:8)
    at RedshiftDataSource.DataSource.queueInvocation.DataSource.ready (c:\src\optum\feasibility-study-api\node_modules\loopback-datasource-juggler\lib\datasource.js:2552:8)
    at stillConnecting (c:\src\optum\feasibility-study-api\node_modules\loopback-datasource-juggler\lib\dao.js:465:18)
    at Function.find (c:\src\optum\feasibility-study-api\node_modules\loopback-datasource-juggler\lib\dao.js:1487:29)
    at PatientDiagnosisRepository.find (c:\src\optum\feasibility-study-api\node_modules\@loopback\repository\src\repositories\legacy-juggler-bridge.ts:286:23)
    at PatientDiagnosisController.find (c:\src\optum\feasibility-study-api\src\controllers\patientdiagnosis.controller.ts:78:50)
    at value_promise_1.transformValueOrPromise.args (c:\src\optum\feasibility-study-api\node_modules\@loopback\context\src\resolver.ts:240:38)
    at Object.transformValueOrPromise (c:\src\optum\feasibility-study-api\node_modules\@loopback\context\src\value-promise.ts:269:12)
    at Object.invokeMethod (c:\src\optum\feasibility-study-api\node_modules\@loopback\context\src\resolver.ts:235:10)
    at ControllerRoute.invokeHandler (c:\src\optum\feasibility-study-api\node_modules\@loopback\rest\src\router\controller-route.ts:126:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:18196) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
warning.js:18
    at _addListener (events.js:247:17)
    at RedshiftDataSource.addListener (events.js:263:10)
    at RedshiftDataSource.once (events.js:292:8)
    at RedshiftDataSource.DataSource.queueInvocation.DataSource.ready (c:\src\optum\feasibility-study-api\node_modules\loopback-datasource-juggler\lib\datasource.js:2553:8)
    at stillConnecting (c:\src\optum\feasibility-study-api\node_modules\loopback-datasource-juggler\lib\dao.js:465:18)
    at Function.find (c:\src\optum\feasibility-study-api\node_modules\loopback-datasource-juggler\lib\dao.js:1487:29)
    at PatientDiagnosisRepository.find (c:\src\optum\feasibility-study-api\node_modules\@loopback\repository\src\repositories\legacy-juggler-bridge.ts:286:23)
    at PatientDiagnosisController.find (c:\src\optum\feasibility-study-api\src\controllers\patientdiagnosis.controller.ts:78:50)
    at value_promise_1.transformValueOrPromise.args (c:\src\optum\feasibility-study-api\node_modules\@loopback\context\src\resolver.ts:240:38)
    at Object.transformValueOrPromise (c:\src\optum\feasibility-study-api\node_modules\@loopback\context\src\value-promise.ts:269:12)
    at Object.invokeMethod (c:\src\optum\feasibility-study-api\node_modules\@loopback\context\src\resolver.ts:235:10)
    at ControllerRoute.invokeHandler (c:\src\optum\feasibility-study-api\node_modules\@loopback\rest\src\router\controller-route.ts:126:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by LotusShiv** [comment]
I have to issue concurrent i.e. parallel REST requests from my loopback method (from my loopback-nodejs api application) and then assemble all the success responses in one array and failed responses in another. I am having tough time finding any documentation or help online for parallel requests and handling of responses. I am using Loopback 3. FYI my nodeJs version is 10.11.x ..  Any help is greatly appreciated
