### ISSUE TITLE
How to configure and use HasManyThrough

### ISSUE THREAD

**Issue by projectxmaker** [strongloop/loopback-datasource-juggler#311]
Hi,

the situation here is I am trying to create a service to handle a enrollment form submission with
. student's name
. student's selected classes

I think about using [HasManyThrough](http://docs.strongloop.com/display/LB/HasManyThrough+relations) to realize this case but it doesn't work as expected, I don't know what's wrong with my approach.

Specifically,

I set up 

##Model Student##
```html
  "relations": {
    "classes": {
      "type": "hasMany",
      "model": "Class",
      "through": "ClassStudent"
    }
  },
```

## Model Class ##
```html
  "relations": {
    "students": {
      "type": "hasMany",
      "model": "Student",
      "through": "ClassStudent"
    }
  },
```

## Model ClassStudent ##
```html
  "relations": {
    "class": {
      "type": "belongsTo",
      "model": "Class",
      "foreignKey": "classId"
    },
    "student": {
      "type": "belongsTo",
      "model": "Student",
      "foreignKey": "studentId"
    }
  },
```

On Explorer, 
I created a Student with service /Students, it returns a Student id

I find following service:
. Method: POST
. URL: /Students/{id}/classes
. recommended to-be-submitted data is as following:
```html
{
  "id": "objectid",
  "classId": "objectid",
  "studentId": "objectid"
}
```

but what it returned in response is an error message 
```html
{
  "error": {
    "name": "ValidationError",
    "status": 422,
    "message": "The `Class` instance is not valid. Details: `name` can't be blank; `name` is blank.",
    "statusCode": 422,
    "details": {
      "context": "Class",
      "codes": {
        "name": [
          "presence",
          "length.blank"
        ]
      },
      "messages": {
        "name": [
          "can't be blank",
          "is blank"
        ]
      }
    },
    "stack": "ValidationError: The `Class` instance is not valid. Details: `name` can't be blank; `name` is blank.\n    at /Users/username/Sites/sv/api/node_modules/loopback-datasource-juggler/lib/dao.js:155:16\n    at ModelConstructor.<anonymous> (/Users/username/Sites/sv/api/node_modules/loopback-datasource-juggler/lib/validations.js:473:13)\n    at ModelConstructor.next (/Users/username/Sites/sv/api/node_modules/loopback-datasource-juggler/lib/hooks.js:66:12)\n    at done (/Users/username/Sites/sv/api/node_modules/loopback-datasource-juggler/lib/validations.js:470:25)\n    at /Users/username/Sites/sv/api/node_modules/loopback-datasource-juggler/lib/validations.js:544:7\n    at process._tickCallback (node.js:419:13)"
  }
}
```

seems it tried to create new Class instead of creating new record of ClassStudent with submitted data: classId and studentId.

plz help O.o

**Comment by raymondfeng** [comment]
It should have been fixed now.
