### ISSUE TITLE
Fail when connector is missing

### ISSUE THREAD

**Issue by frankcarey** [strongloop/loopback-datasource-juggler#320]
Shouldn't the entire thing fail completely instead of just a warning if a connector is missing?
```Javascript
// Currently (my version of code) it just outputs a warning and drives on.
if (!connector) {
    error = util.format('\nWARNING: LoopBack connector "%s" is not installed ' +
      'as any of the following modules:\n\n %s\n\nTo fix, run:\n\n    npm install %s\n',
      name, names.join('\n'), names[names.length -1]);
  }

```

**Comment by jannyHou** [comment]
I think even the error msg starting with `Warning` but it eventually throws error and crashes the app if connector module not found.
See:
```
WARNING: LoopBack connector "db2" is not installed as any of the following modules:

 ./connectors/db2
loopback-connector-db2

To fix, run:

    npm install loopback-connector-db2

/Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback/lib/application.js:243
    throw err;
    ^

Error: Cannot create data source "mydb2": 
WARNING: LoopBack connector "db2" is not installed as any of the following modules:

 ./connectors/db2
loopback-connector-db2

To fix, run:

    npm install loopback-connector-db2

    at DataSource.setup (/Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/datasource.js:308:28)
    at new DataSource (/Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/datasource.js:114:8)
    at Registry.createDataSource (/Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback/lib/registry.js:354:12)
    at dataSourcesFromConfig (/Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback/lib/application.js:435:19)
    at EventEmitter.app.dataSource (/Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback/lib/application.js:233:14)
    at /Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback-boot/lib/executor.js:188:9
    at /Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback-boot/lib/executor.js:279:5
    at Array.forEach (native)
    at forEachKeyedObject (/Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback-boot/lib/executor.js:278:20)
    at setupDataSources (/Users/jannyhou/lb/triage/lb693/loopback-sandbox/node_modules/loopback-boot/lib/executor.js:178:3)
```

I am closing it since the error is handled properly to force user installing a connector.
