### ISSUE TITLE
crash, perhaps on querying whether something is equal to `null`

### ISSUE THREAD

**Issue by sam-github** [strongloop/loopback-datasource-juggler#369]
```

/home/sam/w/sn/strong-pm/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:435
      if (example.near) {
                 ^
TypeError: Cannot read property 'near' of null
    at test (/home/sam/w/sn/strong-pm/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:435:18)
    at /home/sam/w/sn/strong-pm/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:386:12
    at Array.forEach (native)
    at /home/sam/w/sn/strong-pm/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:369:10
    at Array.filter (native)
    at Memory.all (/home/sam/w/sn/strong-pm/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:327:29)
    at Function.find (/home/sam/w/sn/strong-pm/node_modules/loopback-datasource-juggler/lib/dao.js:791:34)
    at SharedMethod.invoke (/home/sam/w/sn/strong-pm/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:224:17)
    at HttpContext.invoke (/home/sam/w/sn/strong-pm/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:247:12)
    at /home/sam/w/sn/strong-pm/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:477:9

```

I was trying various queries in the explorere, I'll see if I can reproduce.

**Comment by guioconnor** [comment]
I'm having the same issue, has there been any development on this?
