### ISSUE TITLE
Object.keys called on non-object

### ISSUE THREAD

**Issue by jorgeramos** [strongloop/loopback-datasource-juggler#651]
I'm using postgresql connector and have an Agency that belongsTo a Charter. Using the API explorer, When I invoke the GET for Agencies/{id} and use the {include:["charter"]} filter the application throws the error below. I dug a little deeper and found the **data** property at that point was actually a JSON string. I was able to circumvent the problem with a try and catch and setting data to JSON.parse(data).

```
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at ModelConstructor.ModelBaseClass._initProperties (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model.js:153:21)
    at ModelConstructor.ModelBaseClass (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model.js:46:8)
    at ModelConstructor (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    at new ModelConstructor (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    at ModelConstructor (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model-builder.js:172:16)
    at ModelConstructor.Object.defineProperty.set [as _address] (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model-builder.js:460:81)
    at ModelConstructor.ModelBaseClass._initProperties (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model.js:177:17)
    at ModelConstructor.ModelBaseClass (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model.js:46:8)
    at ModelConstructor (/Users/myuser/Documents/Sites/myapp/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
```

my temp fix is: 

``` javascript
  var keys;
  try {
    keys = Object.keys(data)
  } catch(e) {
    if(typeof data === 'string') {
      data = JSON.parse(data);
      keys = Object.keys(data);
    }
  }
```

**Comment by PuKoren** [comment]
+1

**Comment by jorgeramos** [comment]
what's strange here is that I have no problems in my scenario if I call the remote GET /Agencies/{id}/charter

**Comment by washcyclist** [comment]
I had a similar error message -- turned out that I hadn't completely defined my related models in the "relations" property of the model definition file, even though I had created properties with "type": "RelatedModel".   Once I defined fully defined the belongTo relations in the "relations" property, the error went away.

**Comment by 0candy** [comment]
Hi @jorgeramos,
Can you fork the loopback-sandbox [https://github.com/strongloop/loopback-sandbox] with a sample repo for me to reproduce the issues?
Thanks.

**Comment by 0candy** [comment]
Closing this issue due to inactivity.
