### ISSUE TITLE
Empty Location Object crash server

### ISSUE THREAD

**Issue by EyMaddis** [strongloop/loopback-datasource-juggler#653]
It's pretty simple, we have a PUT request on an object which has a geolocation property. If I call it with an empty object as the property value, the server will crash!
It seems that there is a try-catch missing somewhere.

## Stacktrace:

```     Uncaught AssertionError: lat must be a number when creating a GeoPoint
      at new GeoPoint (PATH/node_modules/loopback-datasource-juggler/lib/geo.js:152:3)
      at GeoPoint (PATH/node_modules/loopback-datasource-juggler/lib/geo.js:125:12)
      at ModelConstructor.Object.defineProperty.set [as location] (PATH/node_modules/loopback-datasource-juggler/lib/model-builder.js:460:81)
      at ModelConstructor.setAttribute (PATH/node_modules/loopback-datasource-juggler/lib/dao.js:2060:14)
      at ModelConstructor.setAttributes (PATH/node_modules/loopback-datasource-juggler/lib/dao.js:2093:10)
      at PATH/node_modules/loopback-datasource-juggler/lib/dao.js:2209:10
      at PATH/node_modules/loopback-datasource-juggler/lib/observer.js:106:23
      at PATH/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:49:16
      at PATH/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:263:32
      at PATH/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
      at event (PATH/node_modules/loopback-ds-timestamp-mixin/time-stamp.js:28:5)
      at notifySingleObserver (PATH/node_modules/loopback-datasource-juggler/lib/observer.js:98:22)
      at PATH/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:162:20
      at iterate (PATH/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:256:13)
      at process._tickDomainCallback (node.js:381:11)
      at process.<anonymous> (PATH/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)```

**Comment by shawncamp** [comment]
This is also an issue when using MongoDB:
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/geo.js#L148

```
AssertionError: lat must be a number when creating a GeoPoint
    at new GeoPoint (/Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-datasource-juggler/lib/geo.js:156:3)
    at GeoPoint (/Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-datasource-juggler/lib/geo.js:126:12)
    at /Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-datasource-juggler/lib/geo.js:49:13
    at Array.forEach (native)
    at Object.exports.filter (/Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-datasource-juggler/lib/geo.js:42:7)
    at Memory.all (/Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:350:19)
    at geoCallback (/Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-datasource-juggler/lib/dao.js:1401:20)
    at /Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-connector-mongodb/lib/mongodb.js:729:9
    at handleCallback (/Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/shawncamp/Google Drive/code/cosmo/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/cursor.js:842:16
```



When using MongoDB 3.0, the data argument will be in the following format 

```
{ type: 'Point', coordinates: [ -106.26939207, 42.84900248 ] }
```

This is likely not the correct place to fix this issue, however, altering the GeoPoint constructor does work in this condition:

```
function GeoPoint(data) {
  if (!(this instanceof GeoPoint)) {
    return new GeoPoint(data);
  }

  if(arguments.length === 2) {
    data = {
      lat: arguments[0],
      lng: arguments[1]
    };
  }

  assert(Array.isArray(data) || typeof data === 'object' || typeof data === 'string', 'must provide valid geo-coordinates array [lat, lng] or object or a "lat, lng" string');

  if (typeof data === 'string') {
    data = data.split(/,\s*/);
    assert(data.length === 2, 'must provide a string "lat,lng" creating a GeoPoint with a string');
  }
  if (Array.isArray(data)) {
    data = {
      lat: Number(data[0]),
      lng: Number(data[1])
    };
  } else {
    if (data.type === 'Point' && Array.isArray(data.coordinates)) {
      data = {
        lng: Number(data.coordinates[0]),
        lat: Number(data.coordinates[1])
      };
    } else {
      data.lng = Number(data.lng);
      data.lat = Number(data.lat);
    }
  }
```

**Comment by loay** [comment]
Hi @EyMaddis 
It looks like that has been fixed. 
I tested using the test cases and using explorer (using POST then PUT) , the server has not crashed, but it still gives an error message of `"lat must be a number when creating a GeoPoint"`
