### ISSUE TITLE
Memory Connector fails to link two model instances when mapped with hasAndBelongsToMany

### ISSUE THREAD

**Issue by krazineurons** [strongloop/loopback-datasource-juggler#676]
I am following the instructions here
[HasAndBelongsToMany tutorial on loopback](http://docs.strongloop.com/display/public/LB/HasAndBelongsToMany+relations) and created two Models, Patients and Physicians. Also to note that am using the Memory Connector to try out examples.

The models are prepopulated with the following

``` json
{
  "ids": {
    "User": 2,
    "AccessToken": 7,
    "ACL": 1,
    "RoleMapping": 1,
    "Role": 1,
    "Patient": 5,
    "Physician": 3
  },
  "models": {
    "User": [],
    "AccessToken": [],
    "ACL": {},
    "RoleMapping": {},
    "Role": {},
    "Patient": {
      "1": "{\"name\":\"Anirudh\",\"id\":1}",
      "2": "{\"name\":\"Goel\",\"id\":2}",
      "3": "{\"name\":\"New Patient\",\"id\":3}",
      "4": "{\"name\":\"New Patient\",\"id\":4}"
    },
    "Physician": {
      "1": "{\"name\":\"Eyedoctor1\",\"id\":1}",
      "2": "{\"name\":\"Eyedoctor2\",\"id\":2}"
    }
  }
}
```

However when launching the Explorer the put request 
/Physicians/{id}/patients/rel/{fk}
http://localhost:3000/api/Physicians/1/patients/rel/1
is failing with the following error

``` JSON
{
  "error": {
    "name": "TypeError",
    "status": 500,
    "message": "Object.keys called on non-object",
    "stack": "TypeError: Object.keys called on non-object\n    at Function.keys (native)\n    at Memory.all (C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\connectors\\memory.js:316:22)\n    at C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1473:42\n    at doNotify (C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:93:49)\n    at doNotify (C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:93:49)\n    at doNotify (C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:93:49)\n    at Function.ObserverMixin._notifyBaseObservers (C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:116:5)\n    at Function.ObserverMixin.notifyObserversOf (C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:91:8)\n    at Function.ObserverMixin._notifyBaseObservers (C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:114:15)\n    at Function.ObserverMixin.notifyObserversOf (C:\\Users\\anirudh\\Documents\\GitHub\\Hook\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:91:8)"
  }
}
```

Here's the model definition for both as well

``` JSON
{
  "name": "Patient",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "physicians": {
      "type": "hasAndBelongsToMany",
      "model": "Physician",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": []
}
```

``` JSON
{
  "name": "Physician",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "patients": {
      "type": "hasAndBelongsToMany",
      "model": "Patient",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": []
}
```

**Comment by krazineurons** [comment]
@fabien @raymondfeng can you please take a look at it?

**Comment by darior87** [comment]
+1

**Comment by dbe** [comment]
+1 exact same issue

**Comment by mjromper** [comment]
+1

**Comment by wesleymilan** [comment]
+1

**Comment by cfjedimaster** [comment]
Just chiming in that I ran into this today as well.

**Comment by jannyHou** [comment]
> However when launching the Explorer the put request 
/Physicians/{id}/patients/rel/{fk}
http://localhost:3000/api/Physicians/1/patients/rel/1
is failing with the following error

Could anyone having this problem explain why there is a `rel` after `patients` in the endpoint path?
I could not find it in doc and confused where is it defined?

**Comment by loay** [comment]
Hi all, is this still ongoing? If so, can someone, who has the issue still occurring, fork a sandbox sample repo so we can reproduce and debug? Thanks. 

cc @jannyHou

**Comment by loay** [comment]
Closing this for inactivity. Please feel free to leave a comment and I will re-open the issue. Please make sure to provide a sample repo for reproducing and debugging.
