### ISSUE TITLE
referenceMany undefined function error

### ISSUE THREAD

**Issue by jrschumacher** [strongloop/loopback-datasource-juggler#690]
When using a relation like

```
  "relations": {
    "group": {
      "type": "referencesMany",
      "model": "person",
      "foreignKey": "group"
    }
  }
```

The following error will show

```
TypeError: undefined is not a function
    at ModelConstructor.modelFrom.validate.code (/Users/ryan/Projects/38pages/outfit/node_modules/loopback-datasource-juggler/lib/relation-definition.js:2873:25)
    at ModelConstructor.validateCustom (/Users/ryan/Projects/38pages/outfit/node_modules/loopback-datasource-juggler/lib/validations.js:324:24)
```

However removing the defined foreign key fixes it.

```
  "relations": {
    "group": {
      "type": "referencesMany",
      "model": "person",
      "foreignKey": ""
    }
  }
```

**Comment by jrschumacher** [comment]
cc @kozzztya

**Comment by mazesoul** [comment]
Hi @jrschumacher: I believe the reason you this failure is because you are trying to use the same value for the relation name and the FK property name. Also, a referencesMany relationship doesn't support the foreignKey declaration: https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-ReferencesMany

**Comment by rjrahul** [comment]
This issue is occurring even when there is no foreignKey property and "property" property is different from relation name.

Error is coming when we are trying to fetch the data using linked API for example GET http://localhost/api/listing/<id>/tags

where i have a relation 
listing
   relations
      tags
          type: referencesMany
          model: tags

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by 0candy** [comment]
Hi @jrschumacher, not sure if the above comments resolved your issue. I am closing this issue due to inactivity. If you are still running into problems, feel free to leave a comment and I will reopen the issue. Thanks!
