### ISSUE TITLE
App crashes with the error `Error: could not create List from JSON string: "{FR,SA}"`

### ISSUE THREAD

**Issue by dopeddude** [strongloop/loopback-datasource-juggler#714]
The `weekend` property on my model is defined as an array of strings in model.json and on pg db both. The code snippet from model.json is as bellow

```
       "daysOfWeekend": {
			"type": ["string"],
			"required": true,
			"postgresql": {
				"columnName": "weekend",
				"dataType": "Array",
				"dataLength": null,
				"dataPrecision": null,
				"dataScale": null,
				"nullable": false
			}
		},
```

Running query `SELECT weekend as w, weekend[1] as w1, weekend[2] as w2 FROM some_schema.some_table;`  natively on pgsql gives result like `{FR,SA}` for `w` and `FR` for `w1` and `SA` for `w2`, which proves that the data as stored in the table is correct and is essentially an array.

The stack-trace is as bellow:

```

Error: could not create List from JSON string: "{FR,SA}"
    at new List (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/list.js:16:17)
    at List (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/list.js:9:12)
    at ModelConstructor.ModelBaseClass._initProperties (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/model.js:321:28)
    at ModelConstructor.ModelBaseClass (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/model.js:49:8)
    at ModelConstructor (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    at ModelConstructor (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    at new ModelConstructor (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    at /Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/dao.js:1389:19
    at /Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13
    at _each (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:156:9)
    at allCb (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/dao.js:1386:13)
    at /Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:1071:7
    at /Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/observer.js:166:22
    at doNotify (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
    at PostgreSQL.ObserverMixin._notifyBaseObservers (/Users/ashwinikumar/work/1_hs/hotelsoftrzr/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)

```

**Comment by amiashraf** [comment]
I have faced same kind of problem and after checking at the model, I found that I have miss typed the filed type string instead of array. 
When I change it to array then the error gone.

**Comment by dopeddude** [comment]
With type fix on my model-config, the issue was resolved.

**Comment by steventranjs** [comment]
@dopeddude @amiashraf I had the same issue too, How you guys fix this? Thanks.
