### ISSUE TITLE
[AssertionError] The ids argument must be an array

### ISSUE THREAD

**Issue by listepo** [strongloop/loopback-datasource-juggler#735]
Model: 
```json
{
  "name": "Client",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "surname": {
      "type": "string",
      "required": true
    },
    "position": {
      "type": "string",
      "required": true
    },
    "phone": {
      "type": "string",
      "required": true
    },
    "birthday": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "statuses": {
      "type": "referencesMany",
      "model": "ClientStatus",
      "property": "statuses",
      "foreignKey": "statuses"
    }
  },
  "acls": [],
  "methods": {}
}
```
> GET http://localhost:3000/api/Clients/561b8536562e5969dec51a98/statuses
```json
{
  "error": {
    "name": "AssertionError",
    "status": 500,
    "message": "The ids argument must be an array",
    "actual": false,
    "expected": true,
    "operator": "==",
    "generatedMessage": false,
    "stack": "AssertionError: The ids argument must be an array\n    at Function.DataAccessObject.findByIds (/Users/ivan/work/roi4cio/api/node_modules/loopback-datasource-juggler/lib/dao.js:905:3)\n    at ReferencesMany.related (/Users/ivan/work/roi4cio/api/node_modules/loopback-datasource-juggler/lib/relation-definition.js:2966:18)\n    at ScopeDefinition.method [as related] (/Users/ivan/work/roi4cio/api/node_modules/loopback-datasource-juggler/lib/relation-definition.js:727:33)\n    at Function.f (/Users/ivan/work/roi4cio/api/node_modules/loopback-datasource-juggler/lib/scope.js:210:29)\n    at ModelConstructor.fn [as __get__statuses] (/Users/ivan/work/roi4cio/api/node_modules/loopback-datasource-juggler/lib/scope.js:275:7)\n    at SharedMethod.invoke (/Users/ivan/work/roi4cio/api/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:248:25)\n    at HttpContext.invoke (/Users/ivan/work/roi4cio/api/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:384:12)\n    at /Users/ivan/work/roi4cio/api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:620:11\n    at execStack (/Users/ivan/work/roi4cio/api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:460:7)\n    at RemoteObjects.execHooks (/Users/ivan/work/roi4cio/api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:464:10)"
  }
}
```

Problem in ``` ReferencesMany.prototype.related``` (relation-definition.js)

> console.log(fk);

```javascript
statuses
```

> console.log(self);

```javascript
{ password: '$2a$10$VIt0Wf.JDbuvZyuR0fNOIOC2gsMf7qrw8GONZS6/L7TryLOu9LSy6',
  email: 'efcerfvrgv@ecefc.ru',
  name: 'fvrvev',
  surname: 'rvrevrv',
  position: 'rvrvrvr',
  statuses: [ 561b7b10562e5969dec51a59, 561b7b10562e5969dec51a58 ],
  phone: '+09 (989) 898-9879',
  birthday: '2015-10-21T21:00:00.000Z',
  id: 561b8536562e5969dec51a98 }
```

> console.log(typeof ids);

```javascript
function
```

> console.log(ids.toString());

```javascript
function (condOrRefresh, options, cb) {
        if (arguments.length === 0) {
          if (typeof f.value === 'function') {
            return f.value(self);
          } else if (self.__cachedRelations) {
            return self.__cachedRelations[name];
          }
        } else {
          if (typeof condOrRefresh === 'function'
            && options === undefined && cb === undefined) {
            // customer.orders(cb)
            cb = condOrRefresh;
            options = {};
            condOrRefresh = undefined;
          } else if (typeof options === 'function' && cb === undefined) {
            // customer.orders(condOrRefresh, cb);
            cb = options;
            options = {};
          }
          options = options || {}
          // Check if there is a through model
          // see https://github.com/strongloop/loopback/issues/1076
          if (f._scope.collect &&
            condOrRefresh !== null && typeof condOrRefresh === 'object') {
            //extract the paging filters to the through model
            ['limit','offset','skip','order'].forEach(function(pagerFilter){
                if(typeof(condOrRefresh[pagerFilter]) !== 'undefined'){
                    f._scope[pagerFilter] = condOrRefresh[pagerFilter];
                    delete condOrRefresh[pagerFilter];
                }
            });
            // Adjust the include so that the condition will be applied to
            // the target model
            f._scope.include = {
              relation: f._scope.collect,
              scope: condOrRefresh
            };
            condOrRefresh = {};
          }
          return definition.related(self, f._scope, condOrRefresh, options, cb);
        }
      }
```

**Comment by listepo** [comment]
Fix this bug:
 ```javascript 
var ids = self['$'+fk] || [];
```

**Comment by raymondfeng** [comment]
Patch pls?

**Comment by listepo** [comment]
@raymondfeng yes, I will create a PR and test

**Comment by listepo** [comment]
@raymondfeng I found a few places with this problem for ```ReferencesMany```. I think the problem in this codeЖ https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L477

**Comment by listepo** [comment]
@raymondfeng, tests have not worked through this code https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L4801

**Comment by raymondfeng** [comment]
@listepo There is a problem in your model definition:

```
"relations": {
    "statuses": {
      "type": "referencesMany",
      "model": "ClientStatus",
      "property": "statuses",
      "foreignKey": "statuses"
    }
  }
```

The property name should not be the same as the relation name.

**Comment by listepo** [comment]
@raymondfeng I understand you . But I think that there is not very convenient. This is in the documentation? I think you need to add a feature or generate error.

**Comment by raymondfeng** [comment]
We should generate an error for LoopBack 2.x and re-evaluate the convention for 3.x

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
I added a note to docs (https://docs.strongloop.com/display/LB/Creating+model+relations and https://docs.strongloop.com/display/LB/Relation+generator) and created above issue to improve the relation generator CLI tool. 

Can this issue be closed now?

**Comment by listepo** [comment]
:+1:
