### ISSUE TITLE
Loopback app as npm dependency

### ISSUE THREAD

**Issue by FreakTheMighty** [strongloop/loopback-datasource-juggler#894]
When I attempt to consume a loopback application as a dependency of another application the transitive dependencies fail to load despite being installed. Here's some sweet ascii art and the error I get.

```
MyApp --[requires]--> MyLoopbackApp  --[requires]--> loopback-connector-postgresql
```

``` bash
WARNING: LoopBack connector "postgresql" is not installed as any of the following modules:

 ./connectors/postgresql
loopback-connector-postgresql

To fix, run:

    npm install loopback-connector-postgresql

Error: 
WARNING: LoopBack connector "postgresql" is not installed as any of the following modules:

 ./connectors/postgresql
loopback-connector-postgresql

To fix, run:

    npm install loopback-connector-postgresql

    at DataSource.setup (/usr/src/app/node_modules/loopback-datasource-juggler/lib/datasource.js:304:28)
    at new DataSource (/usr/src/app/node_modules/loopback-datasource-juggler/lib/datasource.js:109:8)
    at Registry.createDataSource (/usr/src/app/node_modules/loopback/lib/registry.js:349:12)
    at dataSourcesFromConfig (/usr/src/app/node_modules/loopback/lib/application.js:415:19)
    at EventEmitter.app.dataSource (/usr/src/app/node_modules/loopback/lib/application.js:222:12)
    at /usr/src/app/node_modules/loopback-boot/lib/executor.js:174:9
    at /usr/src/app/node_modules/loopback-boot/lib/executor.js:265:5
    at Array.forEach (native)
    at forEachKeyedObject (/usr/src/app/node_modules/loopback-boot/lib/executor.js:264:20)
    at setupDataSources (/usr/src/app/node_modules/loopback-boot/lib/executor.js:173:3)
    at execute (/usr/src/app/node_modules/loopback-boot/lib/executor.js:32:3)
    at bootLoopBackApp (/usr/src/app/node_modules/loopback-boot/index.js:140:3)
    at Object.<anonymous> (/usr/src/app/node_modules/MyApp/server/server.js:78:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by Amir-61** [comment]
Hey @FreakTheMighty,

I believe I already saw this bug... But could you please give me the steps to reproduce it.

Thanks a lot!

**Comment by FreakTheMighty** [comment]
@loay I did find a work around, but I'm not working on the project anymore - and I don't recall the specific solution.

**Comment by loay** [comment]
Thanks. If you require further assistance concerning the same issue, please let me know.
