### ISSUE TITLE
Using an incorrect 'include' filter kill my loopback app.

### ISSUE THREAD

**Issue by jgpacheco** [strongloop/loopback-datasource-juggler#951]
Passing a wrong 'include' filter to one of the generated find services, shutdown the app with the given error: 

```
TypeError: Cannot read property 'toString' of undefined
    at KVMap.keyToString (/usr/src/app/node_modules/loopback-datasource-juggler/lib/include_utils.js:69:46)
    at Object.KVMap.mapImpl.set (/usr/src/app/node_modules/loopback-datasource-juggler/lib/include_utils.js:75:13)
    at Object.buildOneToOneIdentityMapWithOrigKeys (/usr/src/app/node_modules/loopback-datasource-juggler/lib/include_utils.js:24:11)
    at includeHasManySimple (/usr/src/app/node_modules/loopback-datasource-juggler/lib/include.js:503:36)
    at processIncludeItem (/usr/src/app/node_modules/loopback-datasource-juggler/lib/include.js:280:16)
    at /usr/src/app/node_modules/loopback-datasource-juggler/lib/include.js:178:5
    at /usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13
    at _each (/usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:156:9)
    at Function.Inclusion.include (/usr/src/app/node_modules/loopback-datasource-juggler/lib/include.js:177:9)
```

I know that the filter structure that i'm using is wrong but, should the app shutdown in that manner? Or return an error similar to the error returned when relation name is wrong. Something like that:

```
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Relation \"subZones\" is not defined for Zone model"
  }
}
```

Here is my wrong 'include' filter:

```

{
    include: {
        relation: 'subZones',
        fields: ['name'],
        scope: {
            include: {
                relation: 'segmentControllers'
            }
        }
    }
}
```

**Comment by raymondfeng** [comment]
It's a bug. Can you contribute a patch?

**Comment by jgpacheco** [comment]
Sure, if i can help, tell me what to do. I'm a newbie developer BTW.

**Comment by ASVBPREAUBV** [comment]
Have the same issue. Even with simpler include.
    `filter: {
                limit: 30,
                //offset: 5,
                include: [{
                    relation: 'person', // include the owner object
                }]
      }
`

**Comment by ssh24** [comment]
PR for fix landed: https://github.com/strongloop/loopback-datasource-juggler/pull/1287
