### ISSUE TITLE
Error trying to define relationships in mixins

### ISSUE THREAD

**Issue by jameslk** [strongloop/loopback-datasource-juggler#969]
I'm trying to define a polymorphic relationship in a mixin like so:

``` javascript
module.exports = function SluggableMixin(Model, options) {
    Model.hasMany('UrlSlug', {
        polymorphic: {
            foreignKey: 'sluggableId',
            discriminator: 'sluggableType'
        }
    });
};
```

but I keep running into this error:

```
node_modules/loopback-datasource-juggler/lib/relation-definition.js:610
      modelTo.dataSource.defineProperty(modelTo.modelName, discriminator, { type: 'string', index: true });
                         ^

TypeError: Cannot read property 'defineProperty' of null
    at Function.hasMany (node_modules/loopback-datasource-juggler/lib/relation-definition.js:610:25)
    at Function.hasMany (node_modules/loopback-datasource-juggler/lib/relations.js:73:29)
    at SluggableMixin (src/url-slugs/mixins/sluggable.js:12:11)
    at EventEmitter.<anonymous> (node_modules/loopback-datasource-juggler/lib/mixins.js:37:9)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at DataSource.attach (node_modules/loopback-datasource-juggler/lib/datasource.js:753:14)
    at Function.ModelClass.attachTo (node_modules/loopback-datasource-juggler/lib/model-builder.js:336:16)
    at Registry.configureModel (node_modules/loopback/lib/registry.js:238:15)
    at configureModel (node_modules/loopback/lib/application.js:456:16)
    at EventEmitter.app.model (node_modules/loopback/lib/application.js:133:5)
    at /node_modules/loopback-boot/lib/executor.js:190:9
    at Array.forEach (native)
    at setupModels (node_modules/loopback-boot/lib/executor.js:186:23)
    at execute (node_modules/loopback-boot/lib/executor.js:33:3)
```

I think this may be related to https://github.com/strongloop/loopback/issues/476.

I tried wrapping the entire code in a `Model.on('dataSourceAttached', function() { ... });` event handler, but that never gets fired (I'm guessing it has already been fired).

Then I tried doing it within `Model.app.UrlSlug.on('dataSourceAttached', function() { ... });`, but UrlSlug is undefined at that stage.

So I'm out of ideas. I would think that relationships would be lazily set up when the data source is available instead of being applied immediately against an unavailable data source?

**Comment by fabien** [comment]
Actually, your mixin itself seems fine. Make sure you apply it like this:

`Model.on('attached', function() { Model.mixin('YourMixin', { ... }) })`

**Comment by taoyuan** [comment]
@jameslk 
I have done and it works like this:

```js
module.exports = function SluggableMixin(Model, options) {
  Model.dataSource.defineRelations(Model, {
    slugs: {
      type: 'hasMany',
      model: 'UrlSlug',
      polymorphic: {
        foreignKey: 'sluggableId',
        discriminator: 'sluggableType'
      }
    }
  });
}
```

**Comment by jannyHou** [comment]
Thank you @taoyuan , @jameslk is the solution working for you?
